language: php

php:
  - 5.6
  - 7.0.15
  - 7.1

install:
  - composer install

script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml --coverage-text

after_success:
  - travis_retry php vendor/bin/coveralls
