language: php

php:
  - 5.6
  - 7.0
  - 7.1

install:
  - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls
