site_name: 'Decoy 5'
site_description: 'An awesome CMS'
docs_dir: 'src-docs'
site_dir: 'docs'

pages:
  - Home: index.md
  - Setup: setup.md
  - Getting Started: getting_started.md
  - Models: models.md
  - Views: views.md
  - Controllers: controllers.md
  - Features:
    - Custom Form Fields: custom_form_fields.md
    - Elements: elements.md
    - Images: images.md
    - Localization: localization.md
    - Model Duplication: model_duplication.md
    - Permissions: permissions.md
    - Slugs: slugs.md
    - Validation: validation.md
    - Video Encoding: video_encoding.md
    - Workers: workers.md
    - WYSIWYG: wysiwyg.md

theme: 'material'
extra:
  font:
    text: 'Raleway'
  logo: 'images/decoy-logo-placeholder.png'
  author:
    github: 'bkwld'
    twitter: 'bkwld'

extra_css: ['css/style.css']

markdown_extensions:
  - codehilite(css_class=code)
  - smarty
