# YAML docs:   http://symfony.com/doc/current/components/yaml/yaml_format.html
# YAML editor: http://nodeca.github.io/js-yaml/

# Most terse way of using, like Frags now
homepage:
  marquee:
    title: Welcome to Decoy
