<?php namespace Bkwld\Decoy\Input\EncodingProviders;

/**
 * Interface for service providers for the Encoder class
 */
interface EncoderInterface {

	/**
	 * Tell the service to encode an asset it's source
	 *
	 * @param string $source A string that can be resolved by the encoder
	 *                       to find the source asset.  For instance, an
	 *                       absolute path to the asset on this server
	 * @param callable $callback The callback is sent the following params
	 *                           - string $uid A unique id generated by
	 *                             the service
	 *                           - array $outputs An optional assoc array
	 *                             where the keys are labels for the outputs
	 *                             and the values are absolute paths of
	 *                             where the output will be saved
	 * @return string A GUID to the encode job on the service
	 */
	public function encode($source, $callback);

	/**
	 * 
	 */

}