title: Decoy

theme: jekyll-theme-minimal

nav:
  Setup:
    About: //github.com/BKWLD/decoy
    Installation: index
    Quick start: quick-start
  Core:
    Models: models
    Views: views
    Controllers: controllers
  Features:
    Custom fields: custom-form-fields
    Elements: elements
    Images: images
    Localization: localization
    Model duplication: duplication
    Permissions: permissions
    Slugs: slugs
    Validation: validation
    Video encoding: video-encoding
    Workers: workers
    WYSIWYG: wysiwyg
