# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Decoy
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://www.bukwild.com
baseurl:          /

author:
  name:           'Bukwild'
  url:            http://www.bukwild.com

paginate:         5

# Custom vars
version:          5.2

github:
  repo:           https://github.com/BKWLD/decoy
