title: Decoy

theme: jekyll-theme-minimal

nav:
  Setup:
    About: //github.com/BKWLD/decoy#readme
    Installation: index
    Quick start: quick-start
  Core:
    Models: models
    Views: views
    Controllers: controllers
    Routing: routing
  Features:
    Console: console
    Custom form fields: custom-form-fields
    Elements: elements
    Images: images
    Localization: localization
    Model duplication: duplication
    Permissions: permissions
    Validation: validation
    Video encoding: video-encoding
    WYSIWYG: wysiwyg
