name: Herring Cove
author: Herring Cove
baseurl: 
description: theme for jekyll
github: http://www.github.com/arnp
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: rnpatel[at]me.com
# location: 42°2'16"N   70°12'47"W
# disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


# highlighter: pygments
# markdown: redcarpet
# redcarpet:
  # extensions: ["tables"]

# defaults:
#   - scope:
#       path: ""
#       type: "pages"
#     values:
#       layout: "default"
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"
